#
# file generated by qgraf-3.4.2
#
# output= './QGRAFout/julia/0lSQED.jl' ;
#  style= './styles/julia.sty' ;
# model= './qgraf/SQEDmodel';
#  in= Phi1,  Phi2;
#  out= Phi1,Phi2;
#  loops=           0 ;
# loop_momentum= k;
#  options=  notadpole,nosnail,onshell ;
#

diags=[
(
H           = [-2,1,-1,-4,2,-3],
Hdual       = [0,2,0,0,1,0],
vertex      = [1,1,1,2,2,2],
field       = [Phi1c,Photon,Phi1,Phi2c,Photon,Phi2],
ID          = 1,
pre_factor  = (+1)*1//1,
nprops      = 1,
nloops      = 0,
nin         = 2,
nout        = 2
),
]

